// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHakg6j7GlLr_7hjswxFLHHPeaGTkF-OU',
    appId: '1:243893081042:web:a550bb6c69a736355e6e0b',
    messagingSenderId: '243893081042',
    projectId: 'chat-app-d87fb',
    authDomain: 'chat-app-d87fb.firebaseapp.com',
    storageBucket: 'chat-app-d87fb.appspot.com',
    measurementId: 'G-5EN0JS07X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPeUUhqtdeMKQPg3Fb5baAaFsV_o7n5Lk',
    appId: '1:243893081042:android:8aabdca3a32f3df25e6e0b',
    messagingSenderId: '243893081042',
    projectId: 'chat-app-d87fb',
    storageBucket: 'chat-app-d87fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMQwS0_9l8t75MnekqdgQteqmoHY54W-o',
    appId: '1:243893081042:ios:04e6250dd1a09c2a5e6e0b',
    messagingSenderId: '243893081042',
    projectId: 'chat-app-d87fb',
    storageBucket: 'chat-app-d87fb.appspot.com',
    iosClientId: '243893081042-ib9im9tbha7o5sp2siteb524dqogs5o8.apps.googleusercontent.com',
    iosBundleId: 'com.screendead.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMQwS0_9l8t75MnekqdgQteqmoHY54W-o',
    appId: '1:243893081042:ios:04e6250dd1a09c2a5e6e0b',
    messagingSenderId: '243893081042',
    projectId: 'chat-app-d87fb',
    storageBucket: 'chat-app-d87fb.appspot.com',
    iosClientId: '243893081042-ib9im9tbha7o5sp2siteb524dqogs5o8.apps.googleusercontent.com',
    iosBundleId: 'com.screendead.chatapp.chatApp',
  );
}
